version: '3.8'

services:
  aletheia-mysql:
    image: mysql:8.0
    container_name: aletheia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: aletheia_root
      MYSQL_DATABASE: aletheia_test_data
      MYSQL_USER: aletheia_user
      MYSQL_PASSWORD: aletheia_password
    ports:
      - "3306:3306"
    volumes:
      - aletheia_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  aletheia-postgis:
    image: postgis/postgis:15-3.3
    container_name: aletheia-postgis
    environment:
      POSTGRES_USER: aletheia_pg_user
      POSTGRES_PASSWORD: aletheia_pg_password
      POSTGRES_DB: aletheia_ontology
    ports:
      - "5432:5432"
    volumes:
      - aletheia_pg_data:/var/lib/postgresql/data





  metad0:
    image: vesoft/nebula-metad:v3.6.0
    container_name: aletheia-metad0
    ports:
      - "9559:9559"
    command:
      - --data_path=/data/meta
      - --meta_server_addrs=metad0:9559
      - --port=9559
      - --local_ip=metad0
      - --ws_ip=metad0
      - --ws_http_port=19559
    volumes:
      - aletheia_nebula_meta:/data/meta

  storaged0:
    image: vesoft/nebula-storaged:v3.6.0
    container_name: aletheia-storaged0
    ports:
      - "9779:9779"
    command:
      - --meta_server_addrs=metad0:9559
      - --local_ip=storaged0
      - --ws_ip=storaged0
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
    depends_on:
      - metad0
    volumes:
      - aletheia_nebula_storage:/data/storage

  graphd:
    image: vesoft/nebula-graphd:v3.6.0
    container_name: aletheia-graphd
    ports:
      - "9669:9669"
    command:
      - --meta_server_addrs=metad0:9559
      - --port=9669
      - --ws_ip=graphd
      - --ws_http_port=19669
      - --local_ip=graphd
    depends_on:
      - storaged0
      - metad0

volumes:
  aletheia_mysql_data:
  aletheia_pg_data:
  aletheia_nebula_meta:
  aletheia_nebula_storage:
