"""Legacy graph projection fixtures for demo tenants.

These constants are intentionally isolated from the workbench server entry.
They remain only as bootstrap/demo compatibility while production schema->graph
modeling migrates to SchemaGraphModelingAgent + reviewed projection specs.
"""

SOURCE_LINK_SCHEMAS = {
    "link:employee:1:n:order": {
        "source_table": "employees",
        "source_field": "employees.employeeID",
        "target_table": "orders",
        "target_field": "orders.employeeID",
        "join_condition": "orders.employeeID = employees.employeeID",
        "cardinality": "1:N",
        "graph_edge": "Employee -> Order",
        "source_ref": "orders.employeeID",
    },
    "link:customer:1:n:order": {
        "source_table": "customers",
        "source_field": "customers.customerID",
        "target_table": "orders",
        "target_field": "orders.customerID",
        "join_condition": "orders.customerID = customers.customerID",
        "cardinality": "1:N",
        "graph_edge": "Customer -> Order",
        "source_ref": "orders.customerID",
    },
    "link:category:1:n:product": {
        "source_table": "categories",
        "source_field": "categories.categoryID",
        "target_table": "products",
        "target_field": "products.categoryID",
        "join_condition": "products.categoryID = categories.categoryID",
        "cardinality": "1:N",
        "graph_edge": "Category -> Product",
        "source_ref": "products.categoryID",
    },
    "link:account:1:n:credit_card_transaction": {
        "source_table": "credit_card_transactions_safe",
        "source_field": "credit_card_transactions_safe.accountNumber",
        "target_table": "credit_card_transactions_safe",
        "target_field": "credit_card_transactions_safe.accountNumber",
        "join_condition": "credit_card_transactions_safe.accountNumber = credit_card_transactions_safe.accountNumber",
        "cardinality": "1:N",
        "graph_edge": "Account -> Credit Card Transaction",
        "source_ref": "credit_card_transactions_safe.accountNumber",
    },
    "link:card:1:n:credit_card_transaction": {
        "source_table": "credit_card_transactions_safe",
        "source_field": "credit_card_transactions_safe.cardLast4Digits",
        "target_table": "credit_card_transactions_safe",
        "target_field": "credit_card_transactions_safe.cardLast4Digits",
        "join_condition": "credit_card_transactions_safe.cardLast4Digits = credit_card_transactions_safe.cardLast4Digits",
        "cardinality": "1:N",
        "graph_edge": "Card -> Credit Card Transaction",
        "source_ref": "credit_card_transactions_safe.cardLast4Digits",
    },
    "link:merchant:1:n:credit_card_transaction": {
        "source_table": "credit_card_transactions_safe",
        "source_field": "credit_card_transactions_safe.merchantName",
        "target_table": "credit_card_transactions_safe",
        "target_field": "credit_card_transactions_safe.merchantName",
        "join_condition": "credit_card_transactions_safe.merchantName = credit_card_transactions_safe.merchantName",
        "cardinality": "1:N",
        "graph_edge": "Merchant -> Credit Card Transaction",
        "source_ref": "credit_card_transactions_safe.merchantName",
    },
    "link:country:n:m:chokepoint_dependency": {
        "source_table": "maritime_chokepoint_country_dependencies",
        "source_field": "maritime_chokepoint_country_dependencies.iso3",
        "target_table": "maritime_chokepoint_risk_indicators",
        "target_field": "maritime_chokepoint_risk_indicators.canal",
        "join_condition": "maritime_chokepoint_country_dependencies.canal = maritime_chokepoint_risk_indicators.canal",
        "cardinality": "N:M",
        "graph_edge": "Country -> Chokepoint",
        "source_ref": "maritime_chokepoint_country_dependencies.canal",
    },
    "link:chokepoint:1:n:risk_indicator": {
        "source_table": "maritime_chokepoint_risk_indicators",
        "source_field": "maritime_chokepoint_risk_indicators.canal",
        "target_table": "maritime_chokepoint_risk_indicators",
        "target_field": "maritime_chokepoint_risk_indicators.risk_indicator_id",
        "join_condition": "risk_indicator.canal = chokepoint.canal",
        "cardinality": "1:N",
        "graph_edge": "Chokepoint -> RiskIndicator",
        "source_ref": "maritime_chokepoint_risk_indicators.canal",
    },
    "link:country:1:n:systemic_risk_result": {
        "source_table": "maritime_chokepoint_country_dependencies",
        "source_field": "maritime_chokepoint_country_dependencies.iso3",
        "target_table": "maritime_chokepoint_systemic_risk_results",
        "target_field": "maritime_chokepoint_systemic_risk_results.iso3",
        "join_condition": "maritime_chokepoint_country_dependencies.iso3 = maritime_chokepoint_systemic_risk_results.iso3",
        "cardinality": "1:N",
        "graph_edge": "Country -> SystemicRiskResult",
        "source_ref": "maritime_chokepoint_systemic_risk_results.iso3",
    },
    "link:trade_dependency:n:1:country": {
        "source_table": "maritime_chokepoint_country_dependencies",
        "source_field": "maritime_chokepoint_country_dependencies.dependency_id",
        "target_table": "maritime_chokepoint_country_dependencies",
        "target_field": "maritime_chokepoint_country_dependencies.iso3",
        "join_condition": "trade_dependency.iso3 = country.iso3",
        "cardinality": "N:1",
        "graph_edge": "TradeDependency -> Country",
        "source_ref": "maritime_chokepoint_country_dependencies.iso3",
    },
    "link:trade_dependency:n:1:chokepoint": {
        "source_table": "maritime_chokepoint_country_dependencies",
        "source_field": "maritime_chokepoint_country_dependencies.dependency_id",
        "target_table": "maritime_chokepoint_risk_indicators",
        "target_field": "maritime_chokepoint_risk_indicators.canal",
        "join_condition": "trade_dependency.canal = chokepoint.canal",
        "cardinality": "N:1",
        "graph_edge": "TradeDependency -> Chokepoint",
        "source_ref": "maritime_chokepoint_country_dependencies.canal",
    },
    "link:risk_finding:n:m:evidence": {
        "source_table": "maritime_chokepoint_systemic_risk_results",
        "source_field": "maritime_chokepoint_systemic_risk_results.risk_result_id",
        "target_table": "maritime_chokepoint_risk_indicators",
        "target_field": "maritime_chokepoint_risk_indicators.canal",
        "join_condition": "risk_finding.canal = risk_indicator.canal",
        "cardinality": "N:M",
        "graph_edge": "RiskFinding -> RiskIndicator",
        "source_ref": "maritime_chokepoint_systemic_risk_results.canal",
    },
    "link:mitigation_action:n:1:risk_finding": {
        "source_table": "maritime_chokepoint_systemic_risk_results",
        "source_field": "maritime_chokepoint_systemic_risk_results.risk_result_id",
        "target_table": "maritime_chokepoint_systemic_risk_results",
        "target_field": "maritime_chokepoint_systemic_risk_results.risk_result_id",
        "join_condition": "mitigation_action.risk_result_id = risk_finding.risk_result_id",
        "cardinality": "N:1",
        "graph_edge": "MitigationAction -> RiskFinding",
        "source_ref": "maritime_chokepoint_systemic_risk_results.risk_result_id",
    },
    "link:conflict_event:1:n:economic_channel": {
        "source_table": "us_iran_war_graph_edges",
        "source_field": "us_iran_war_graph_edges.source_node",
        "target_table": "us_iran_war_graph_edges",
        "target_field": "us_iran_war_graph_edges.target_node",
        "join_condition": "graph_edges.relation = 'raises_risk_of'",
        "cardinality": "1:N",
        "graph_edge": "ConflictEvent -> EconomicChannel",
        "source_ref": "us_iran_war_graph_edges.relation",
    },
    "link:economic_channel:1:n:country_exposure": {
        "source_table": "us_iran_war_graph_edges",
        "source_field": "us_iran_war_graph_edges.source_node",
        "target_table": "us_iran_war_graph_edges",
        "target_field": "us_iran_war_graph_edges.target_node",
        "join_condition": "graph_edges.relation = 'impacts'",
        "cardinality": "1:N",
        "graph_edge": "EconomicChannel -> CountryExposure",
        "source_ref": "us_iran_war_graph_edges.relation",
    },
    "link:country_exposure:n:m:recommended_action": {
        "source_table": "us_iran_war_graph_edges",
        "source_field": "us_iran_war_graph_edges.source_node",
        "target_table": "us_iran_war_graph_edges",
        "target_field": "us_iran_war_graph_edges.target_node",
        "join_condition": "graph_edges.relation = 'requires_action'",
        "cardinality": "N:M",
        "graph_edge": "CountryExposure -> RecommendedAction",
        "source_ref": "us_iran_war_graph_edges.relation",
    },
    "link:source_document:n:m:evidence": {
        "source_table": "us_iran_war_web_sources",
        "source_field": "us_iran_war_web_sources.source_id",
        "target_table": "us_iran_war_graph_edges",
        "target_field": "us_iran_war_graph_edges.source_id",
        "join_condition": "us_iran_war_web_sources.source_id = us_iran_war_graph_edges.source_id",
        "cardinality": "N:M",
        "graph_edge": "SourceDocument -> GraphEdge",
        "source_ref": "us_iran_war_graph_edges.source_id",
    },
}

GRAPH_ENTITY_CONFIG = {
    "employee": {"table": "employees", "pk": "employeeID", "label_cols": ["firstName", "lastName"], "label_join": " ", "artifact": "object:employee"},
    "order":    {"table": "orders",    "pk": "orderID",    "label_cols": ["orderID"],                "label_fmt": "Order #{}", "artifact": "object:order"},
    "customer": {"table": "customers", "pk": "customerID","label_cols": ["companyName"],             "label_join": "",       "artifact": "object:customer"},
    "product":  {"table": "products",  "pk": "productID", "label_cols": ["productName"],             "label_join": "",       "artifact": "object:product"},
    "category": {"table": "categories","pk": "categoryID","label_cols": ["categoryName"],            "label_join": "",       "artifact": "object:category"},
    "credit_card_transaction": {
        "type": "CreditCardTransaction",
        "label": "Credit Card Transaction",
        "table": "credit_card_transactions_safe",
        "pk": "transaction_id",
        "label_cols": ["transaction_id", "merchantName"],
        "label_fmt": "Transaction #{}",
        "artifact": "object:credit_card_transaction",
    },
    "account": {
        "type": "Account",
        "table": "credit_card_transactions_safe",
        "pk": "accountNumber",
        "label_cols": ["accountNumber", "customerId"],
        "label_fmt": "Account {}",
        "artifact": "object:account",
        "distinct": True,
    },
    "card": {
        "type": "Card",
        "table": "credit_card_transactions_safe",
        "pk": "cardLast4Digits",
        "label_cols": ["cardLast4Digits"],
        "label_fmt": "Card ****{}",
        "artifact": "object:card",
        "distinct": True,
    },
    "merchant": {
        "type": "Merchant",
        "table": "credit_card_transactions_safe",
        "pk": "merchantName",
        "label_cols": ["merchantName", "merchantCategoryCode"],
        "label_join": " · ",
        "artifact": "object:merchant",
        "distinct": True,
    },
    "chokepoint": {
        "type": "Chokepoint",
        "table": "maritime_chokepoint_risk_indicators",
        "pk": "risk_indicator_id",
        "label_cols": ["canal"],
        "label_join": "",
        "artifact": "object:chokepoint",
    },
    "country": {
        "type": "Country",
        "table": "maritime_chokepoint_country_dependencies",
        "pk": "iso3",
        "label_cols": ["iso3"],
        "label_join": "",
        "artifact": "object:country",
        "distinct": True,
    },
    "trade_dependency": {
        "type": "TradeDependency",
        "table": "maritime_chokepoint_country_dependencies",
        "pk": "dependency_id",
        "label_cols": ["iso3", "canal"],
        "label_join": " · ",
        "artifact": "object:trade_dependency",
    },
    "hazard": {
        "type": "Hazard",
        "table": "maritime_chokepoint_risk_indicators",
        "pk": "risk_indicator_id",
        "label_cols": ["canal"],
        "label_fmt": "Hazards at {}",
        "artifact": "object:hazard",
    },
    "risk_indicator": {
        "type": "RiskIndicator",
        "table": "maritime_chokepoint_risk_indicators",
        "pk": "risk_indicator_id",
        "label_cols": ["canal"],
        "label_fmt": "Risk indicators at {}",
        "artifact": "object:risk_indicator",
    },
    "systemic_risk_result": {
        "type": "SystemicRiskResult",
        "table": "maritime_chokepoint_systemic_risk_results",
        "pk": "risk_result_id",
        "label_cols": ["iso3", "canal"],
        "label_join": " · ",
        "artifact": "object:systemic_risk_result",
    },
    "risk_finding": {
        "type": "RiskFinding",
        "table": "maritime_chokepoint_systemic_risk_results",
        "pk": "risk_result_id",
        "label_cols": ["iso3", "canal"],
        "label_fmt": "Finding candidate {}",
        "artifact": "object:risk_finding",
    },
    "mitigation_action": {
        "type": "MitigationAction",
        "table": "maritime_chokepoint_systemic_risk_results",
        "pk": "risk_result_id",
        "label_cols": ["iso3", "canal"],
        "label_fmt": "Action candidate {}",
        "artifact": "object:mitigation_action",
    },
}

GRAPH_LINK_CONFIG = [
    {"link": "link:employee:1:n:order",       "from": "employee", "to": "order",    "fk_table": "orders",    "fk_col": "employeeID"},
    {"link": "link:customer:1:n:order",        "from": "customer", "to": "order",    "fk_table": "orders",    "fk_col": "customerID"},
    {"link": "link:category:1:n:product",      "from": "category", "to": "product",  "fk_table": "products",  "fk_col": "categoryID"},
    {"link": "link:order:n:m:product",          "from": "order",    "to": "product",  "fk_table": "order_details", "fk_col": "orderID", "target_fk": "productID"},
    {"link": "link:employee:1:n:employee",      "from": "employee", "to": "employee", "fk_table": "employees", "fk_col": "reportsTo", "reverse": True},
    {"link": "link:account:1:n:credit_card_transaction", "from": "account", "to": "credit_card_transaction", "fk_table": "credit_card_transactions_safe", "fk_col": "accountNumber"},
    {"link": "link:card:1:n:credit_card_transaction", "from": "card", "to": "credit_card_transaction", "fk_table": "credit_card_transactions_safe", "fk_col": "cardLast4Digits"},
    {"link": "link:merchant:1:n:credit_card_transaction", "from": "merchant", "to": "credit_card_transaction", "fk_table": "credit_card_transactions_safe", "fk_col": "merchantName"},
]
