#!/bin/bash

# Aletheia: Run Deep Ontology Graph Reasoning with LIVE Data

if [ -d "../.venv" ]; then
    source ../.venv/bin/activate
elif [ -d ".venv" ]; then
    source .venv/bin/activate
fi

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$PROJECT_ROOT"

echo "================================================="
echo "Starting Aletheia Deep Ontology Reasoning Phase..."
echo "================================================="

# Detect model based on env vars
if [ -n "$GEMINI_API_KEY" ]; then
    MODEL="gemini/gemini-3.1-pro-preview"
elif [ -n "$OPENAI_API_KEY" ]; then
    MODEL="gpt-4o"
else
    echo "⚠️ Error: No API Key found. Please export GEMINI_API_KEY or OPENAI_API_KEY."
    exit 1
fi

echo "Using Model: $MODEL"

echo "-------------------------------------------------"
echo "Executing Graph Queries against Nebula Database..."
echo "Extracting Subgraphs & Performing Business Inference"
echo "-------------------------------------------------"

# Clear previous runtime results
> run_reasoning_result.md
echo "# Aletheia: Dynamic Graph Reasoning Report" > run_reasoning_result.md
echo "This document captures the dynamic business insights generated by combining the Semantic Meta-Graph with LIVE Subgraph Data from Nebula." >> run_reasoning_result.md

python agents/ontology_reasoning_agent.py --model "$MODEL"

echo "================================================="
echo "Done! Deep Ontology Reasoning completed."
echo "================================================="
